### ISSUE TITLE
it takes an error at phusion passenger 

### ISSUE THREAD

**Issue by miraten** [meteorhacks/kadira#122]
I'm running my app at phusion passenger. 4.0.53 
And the server OS is centOS 6.3

Running the app, there is an error as following:
# 

Error: EACCES, permission denied
App 34327 stderr:   at [object Object].SystemModel.buildPayload (/home/www/bookpal/site_www/programs/server/packages/meteorhacks_kadira.js:1082:28)
App 34327 stderr:   at Object.Kadira._buildPayload (/home/www/bookpal/site_www/programs/server/packages/meteorhacks_kadira.js:1341:42)
App 34327 stderr:   at /home/www/bookpal/site_www/programs/server/packages/meteorhacks_kadira.js:1420:26
# 

At first, the server seems to work well.
However, after some seconds, the app tries to restart to fail several times.
About 1~3 minutes later, the server works but to restart again, again.

Excluding the Kadira configuration, the server works well and does not restart again.

What is the solution?

**Comment by dropfen** [comment]
@arunoda might be very interesting to read about your experience with passenger and what do you think about the compatibility with meteor at all, thanks in advise 

PS: It's ok when it's not in this topic ;)
