### ISSUE TITLE
kadira error

### ISSUE THREAD

**Issue by dan335** [meteorhacks/kadira#129]
Found this in the logs.

/opt/dominus/app/programs/server/packages/meteorhacks_kadira.js:3156
      throw err;                                                              
            ^
RangeError: targetStart out of bounds
    at Buffer.copy (buffer.js:526:11)
    at [object Object].StringDecoder.write (string_decoder.js:89:12)
    at readableAddChunk (_stream_readable.js:153:31)
    at IncomingMessage.Readable.push (_stream_readable.js:127:10)
    at HTTPParser.parserOnBody [as onBody] (http.js:142:22)
    at CleartextStream.socketOnData [as ondata] (http.js:1587:20)
    at CleartextStream.read [as _read] (tls.js:513:12)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at CleartextStream.read [as _read] (tls.js:519:12)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
error: Forever detected script exited with code: 7
error: Script restart attempt #1

**Comment by arunoda** [comment]
Actually, Kadira in the logs because we track uncaught exceptions. Seems
like an issue HTTP. Not sure though.

**Comment by dan335** [comment]
Ok thanks.  I'm not sure where it's from.  Could be knox or Meteor HTTP.get.
