### ISSUE TITLE
Kadira is throwing "Cannot set property '_activeAt' of null" error 

### ISSUE THREAD

**Issue by Dsyko** [meteorhacks/kadira#130]
Our server has crashed a couple of times, and each time right before the crash Kadira is throwing the following error:

    /app/.meteor/heroku_build/app/programs/server/packages/meteorhacks_kadira.js:3039
    throw err;
    Cannot set property '_activeAt' of null
       at [object Object].SystemModel.handleSessionActivity     (packages/meteorhacks:kadira/lib/models/system.js:68:1)
       at [object Object].serverProto._handleConnect     (packages/meteorhacks:kadira/lib/hijack/wrap_server.js:8:1)
       at packages/ddp/livedata_server.js:1266:1

Not sure if this is causing our server to crash, or if some other issue is coming up which also causes this error to be thrown.

Maybe the variable 'session' should be guarded before trying to set the _activeAt key on it. 

    if(session){
        session._activeAt = Date.now()
    }

**Comment by arunoda** [comment]
Working on it. Will give a fix soon.

**Comment by Dsyko** [comment]
Ok cool, thanks!

**Comment by arunoda** [comment]
There is a new version published with the fix. Anyway, please tell me your
Meteor version I can find for the real issue.

**Comment by Dsyko** [comment]
Thanks I'll bump our Kadira version, we are on Meteor 1.0.2.1

**Comment by arunoda** [comment]
Okay. thanks.
