### ISSUE TITLE
Cannot read property 'trace' of undefined

### ISSUE THREAD

**Issue by LarsBuur** [meteorhacks/kadira#140]
I am not really doing any funky stuff here - the only thing I did was updating kadira using meteor update. Now my app crashes once in a while. If I find some pattern in the error I will report again.

```
 TypeError: Cannot read property 'trace' of undefined
   at [object Object].sessionProto.protocol_handlers.sub (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:65:1)
   at packages/ddp/livedata_server.js:546:1

=> Exited with code: 7
=> Your application is crashing. Waiting for file change.
```

**Comment by arunoda** [comment]
Okay. Let me see. What's your Meteor version.

**Comment by LarsBuur** [comment]
Sorry. Should have mentioned. Meteor 1.0.3.1


```
meteor list
accounts-password        1.0.6  Password support for accounts
alanning:roles           1.2.13  Role-based authorization
gadicohen:headers        0.0.27  Access HTTP headers on both server and client
iron:router              1.0.7  Routing specifically designed for Meteor
larsbuur:numeral         1.5.5+ Package to wrap Numeral-js, a library for formatting and manipulating numbers
markdown                 1.0.3  Markdown-to-HTML processor
meteor-platform          1.2.1  Include a standard set of Meteor packages in your app
meteorhacks:kadira       2.19.4  Performance Monitoring for Meteor
msavin:sessioninspector  1.2.1  View and edit all your session variables in the browser.
nooitaf:semantic-ui      1.9.1  Semantic UI packaged for Meteor
ongoworks:speakingurl    1.0.5  Generate a slug. Wraps the speakingurl package for Meteor
percolate:momentum       0.5.2+ Reactive animations
random                   1.0.2  Random number generator and utilities
reywood:iron-router-ga   0.5.3  Google analytics (universal edition) with some Iron Router sugar for tracking page views.
tap:i18n                 1.4.0  A comprehensive internationalization solution for Meteor


+ These packages are built locally from source.
```

**Comment by arunoda** [comment]
BTW: This is something very strange to happen (actually impossible).
If you could find some pattern, let me know. I like to know the reason.

**Comment by LarsBuur** [comment]
I will.

**Comment by arunoda** [comment]
I found a potential reason for this and made a new version.
Try that `v2.19.6`

If you can't get that version try `meteor refresh` once and update kadira

**Comment by LarsBuur** [comment]
The latest version solved the issue. Closing this one.

**Comment by arunoda** [comment]
Great.
