### ISSUE TITLE
Kadira error for meteor release 1.0.4.1

### ISSUE THREAD

**Issue by rnarayan** [meteorhacks/kadira#143]
When I run my app with meteor run --release 1.0.4, I get the following error. Please note that this error is repeated for every route in the app. The app runs fine under release 1.0.4.1 if I remove kadira.

I20150318-21:14:13.947(-5)? Internal exception while processing message { msg: 'method',
I20150318-21:14:13.947(-5)?   method: 'login',
I20150318-21:14:13.948(-5)?   params: [ { resume: 'hPFvnBdrSbgIcKs79DhkrJLRn-WDkw3pEXxo7C6qJos' } ],
I20150318-21:14:13.948(-5)?   id: '1' } Object  has no method 'map' TypeError: Object  has no method 'map'
I20150318-21:14:13.948(-5)?     at [object Object].WaitTimeBuilder.register (packages/meteorhacks:kadira/lib/wait_time_builder.js:14:1)
I20150318-21:14:13.948(-5)?     at [object Object].sessionProto.processMessage (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:12:1)
I20150318-21:14:13.948(-5)?     at SockJSConnection.<anonymous> (packages/ddp/livedata_server.js:1292:1)
I20150318-21:14:13.948(-5)?     at SockJSConnection.emit (events.js:95:17)
I20150318-21:14:13.948(-5)?     at Session.didMessage (/home/newgeek/.meteor/packages/ddp/.1.1.0.j8e7un++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/transport.js:246:25)
I20150318-21:14:13.948(-5)?     at WebSocketReceiver.didMessage (/home/newgeek/.meteor/packages/ddp/.1.1.0.j8e7un++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:99:40)
I20150318-21:14:13.949(-5)?     at [object Object].<anonymous> (/home/newgeek/.meteor/packages/ddp/.1.1.0.j8e7un++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:70:24)
I20150318-21:14:13.949(-5)?     at [object Object].emit (events.js:95:17)
I20150318-21:14:13.949(-5)?     at [object Object].EventTarget.dispatchEvent (/home/newgeek/.meteor/packages/ddp/.1.1.0.j8e7un++os+web.browser+web.cordova/npm/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
I20150318-21:14:13.949(-5)?     at [object Object].instance._receiveMessage (/home/newgeek/.meteor/packages/ddp/.1.1.0.j8e7un++os+web.browser+web.cordova/npm/node_modules/faye-websocket/lib/faye/websocket/api.js:129:10)
I20150318-21:14:13.955(-5)? Internal exception while processing message { msg: 'sub',
I20150318-21:14:13.955(-5)?   id: 'Hmp2xFoM8oDazZxPr',
I20150318-21:14:13.955(-5)?   name: 'meteor.loginServiceConfiguration',
I20150318-21:14:13.956(-5)?   params: [] } Object  has no method 'map' TypeError: Object  has no method 'map'
I20150318-21:14:13.956(-5)?     at [object Object].WaitTimeBuilder.register (packages/meteorhacks:kadira/lib/wait_time_builder.js:14:1)
I20150318-21:14:13.956(-5)?     at [object Object].sessionProto.processMessage (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:12:1)
I20150318-21:14:13.956(-5)?     at SockJSConnection.<anonymous> (packages/ddp/livedata_server.js:1292:1)
I20150318-21:14:13.956(-5)?     at SockJSConnection.emit (events.js:95:17)
I20150318-21:14:13.956(-5)?     at Session.didMessage (/home/newgeek/.meteor/packages/ddp/.1.1.0.j8e7un++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/transport.js:246:25)
I20150318-21:14:13.956(-5)?     at WebSocketReceiver.didMessage (/home/newgeek/.meteor/packages/ddp/.1.1.0.j8e7un++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:99:40)
I20150318-21:14:13.956(-5)?     at [object Object].<anonymous> (/home/newgeek/.meteor/packages/ddp/.1.1.0.j8e7un++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:70:24)
I20150318-21:14:13.957(-5)?     at [object Object].emit (events.js:95:17)
I20150318-21:14:13.957(-5)?     at [object Object].EventTarget.dispatchEvent (/home/newgeek/.meteor/packages/ddp/.1.1.0.j8e7un++os+web.browser+web.cordova/npm/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
I20150318-21:14:13.957(-5)?     at [object Object].instance._receiveMessage (/home/newgeek/.meteor/packages/ddp/.1.1.0.j8e7un++os+web.browser+web.cordova/npm/node_modules/faye-websocket/lib/faye/websocket/api.js:129:10)

**Comment by arunoda** [comment]
We've fixed this issue.
Try updating kadira.

**Comment by arunoda** [comment]
See you've the latest version. Check .meteor/versions as well.
Latest version is: 2.20.0

**Comment by roelvan** [comment]
Version 2.20.0 gives me a different kind of error:
```
Exception from sub bookingMetrics id GtcreyyfQiSehg6w2 TypeError: Cannot call method 'call' of undefined
    at OptimizedApply (packages/meteorhacks:kadira/lib/utils.js:27:1)
    at Object.ret.(anonymous function) [as _getDb] (packages/meteorhacks:kadira/lib/hijack/db.js:16:1)
    at [object Object].Mongo.Collection._getDb (packages/meteorhacks:collection-utils/index.js:14:1)
    at [object Object].Mongo.Collection._getCollection (packages/meteorhacks:collection-utils/index.js:26:1)
    at [object Object].Mongo.Collection.aggregate (packages/meteorhacks:aggregate/index.js:3:1)
    at [object Object].Metrics._prepareData (packages/metrics-aggregations/lib/server.coffee:12:62)
    at [object Object].Metrics._publishCursor (packages/metrics-aggregations/lib/server.coffee:15:13)
    at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:986:1)
    at [object Object].MeteorX.Subscription._runHandler (packages/meteorhacks:unblock/lib/unblock.js:47:1)
    at [object Object].subscriptionProto._runHandler (packages/meteorhacks:kadira/lib/hijack/wrap_subscription.js:12:1)
Exception from sub paymentsBalanceData id XrS9PzYTTomro82aN TypeError: Cannot call method 'call' of undefined
    at OptimizedApply (packages/meteorhacks:kadira/lib/utils.js:27:1)
    at Object.r[128.199.43.76] et.(anonymous function) [as _getDb] (packages/meteorhacks:kadira/lib/hijack/db.js:16:1)
    at [object Object].Mongo.Collection._getDb (packages/meteorhacks:collection-utils/index.js:14:1)
    at [object Object].Mongo.Collection._getCollection (packages/meteorhacks:collection-utils/index.js:26:1)
    at [object Object].Mongo.Collection.aggregate (packages/meteorhacks:aggregate/index.js:3:1)
    at [object Object].Metrics._prepareData (packages/metrics-aggregations/lib/server.coffee:12:62)
    at [object Object].Metrics._publishCursor (packages/metrics-aggregations/lib/server.coffee:15:13)
    at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:986:1)
    at [object Object].MeteorX.Subscription._runHandler (packages/meteorhacks:unblock/lib/unblock.js:47:1)
    at [object Object].subscriptionProto._runHandler (packages/meteorhacks:kadira/lib/hijack/wrap_subscription.js:12:1)
Exception from sub bookingChartData id qDowr8GcErmNZAPiA TypeError: Cannot call method 'call' of undefined
    at OptimizedApply (packages/meteorhacks:kadira/lib/utils.js:27:1)
    at Object.ret.(anonymous function) [as _getDb] (packages/meteorhacks:kadira/lib/hijack/db.js:16:1)
    at [object Object].Mongo.Collection._getDb (packages/meteorhacks:collection-utils/index.js:14:1)
    at [object Object].Mongo.Collection._getCollection (packages/meteorhacks:collection-utils/index.js:26:1)
    at [object Object].Mongo.Collection.aggregate (packages/meteorhacks:aggregate/index.js:3:1)
    at [object Object].Metrics._prepareData (packages/metrics-aggregations/lib/server.coffee:12:62)
    at [object Object].Metrics._publishCursor (packages/metrics-aggregations/lib/server.coffee:15:13)
    at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:986:1)
    at [object Object].MeteorX.Subscription._runHandler (packages/meteorhacks:unblock/lib/unblock.js:47:1)
    at [object Object].subscriptionProto._runHandler (packages/meteorhacks:kadira/lib/hijack/wrap_subscription.js:12:1)
```

**Comment by arunoda** [comment]
Okay. Seems like you are using meteorhacks:aggregate.
Update that too.

**Comment by roelvan** [comment]
Yep I have the latest `1.2.0` version for meteor-aggregate

**Comment by arunoda** [comment]
That seems weird.

**Comment by arunoda** [comment]
What's the collection you are aggregating?

**Comment by rnarayan** [comment]
I upgraded Kadira to 2.20.0 and it resolved my issue. Thanks.

**Comment by arunoda** [comment]
hey @roelvan 

I fixed a potential issue.
You can give it a try.

**Comment by roelvan** [comment]
I am aggregating a `Bookings` collection. Will try your fix today.

**Comment by roelvan** [comment]
Yep `v.2.20.1` did the trick! No more errors in my logs. Thanks man!

**Comment by arunoda** [comment]
Nice. Let keep this open for few days and close.

**Comment by javaknight** [comment]
also encountered the same issue. I can't update to fix it though. 

$ meteor update
myapp: updated to Meteor 1.0.5.
Your packages are at their latest compatible versions.
$ meteor list
insecure            1.0.3  Allow all database writes by default
meteor-platform     1.2.2  Include a standard set of Meteor packages in your app
meteorhacks:kadira  2.15.0* Performance Monitoring for Meteor
momentjs:moment     2.9.0  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
* New versions of these packages are available! Run 'meteor update' to try to update those packages to their latest versions. If your packages cannot be updated further, try typing `meteor add <package>@<newVersion>` to see more
  information.

+ These packages are built locally from source.
$ meteor update
This project is already at Meteor 1.0.5, the latest release.
Your packages are at their latest compatible versions.
$ meteor show meteorhacks:kadira
Package: meteorhacks:kadira@2.20.1
Maintainers: meteorhacks
Git: https://github.com/meteorhacks/kadira.git
Exports: Kadira

[![](https://api.travis-ci.org/meteorhacks/kadira.svg)](https://travis-ci.org/meteorhacks/kadira)

Recent versions:
  2.19.4  February 18th, 2015
  2.19.5  February 20th, 2015
  2.19.6  February 20th, 2015
  2.20.0  March 17th, 2015
  2.20.1  March 19th, 2015
$ meteor add meteorhacks:kadira@2.20.1
 => Errors while adding packages:

While selecting package versions:
error: conflict: constraints on meteorhacks:meteorx cannot be satisfied.
Constraints come from:
<top level>
meteorhacks:kadira@2.20.1

**Comment by arunoda** [comment]
Can I have your .meteor/packages and .meteor/versions file?
Seems like a conflict. Let's see.

**Comment by javaknight** [comment]
Sure

$ cat packages
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
insecure
amqp
meteorhacks:kadira
momentjs:moment

$ cat versions
amqp@0.0.0
autoupdate@1.2.0
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.0
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
check@1.0.5
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
email@1.0.6
fastclick@1.0.3
geojson-utils@1.0.3
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
id-map@1.0.3
insecure@1.0.3
jquery@1.11.3_2
json@1.0.3
launch-screen@1.0.2
livedata@1.0.13
localstorage@1.0.3
logging@1.0.7
meteor@1.1.5
meteor-platform@1.2.2
meteorhacks:kadira@2.15.0
meteorhacks:kadira-binary-deps@1.3.1
meteorhacks:meteorx@1.2.0
minifiers@1.1.4
minimongo@1.0.7
mobile-status-bar@1.0.3
momentjs:moment@2.9.0
mongo@1.1.0
mongo-livedata@1.0.8
observe-sequence@1.0.5
ordered-dict@1.0.3
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
routepolicy@1.0.5
session@1.1.0
spacebars@1.0.6
spacebars-compiler@1.0.5
templating@1.1.0
tracker@1.0.6
ui@1.0.6
underscore@1.0.3
url@1.0.4
webapp@1.2.0
webapp-hashing@1.0.3

**Comment by arunoda** [comment]
Weird.
Try to remove kadira completely and add it back.

**Comment by javaknight** [comment]
$ meteor remove meteorhacks:kadira

Changes to your project's package version selections:

email                           removed from your project
localstorage                    removed from your project
meteorhacks:kadira              removed from your project
meteorhacks:kadira-binary-deps  removed from your project
meteorhacks:meteorx             removed from your project
mongo-livedata                  removed from your project

meteorhacks:kadira: removed dependency
$ meteor add meteorhacks:kadira

Changes to your project's package version selections:

email                           added, version 1.0.6
localstorage                    added, version 1.0.3
meteorhacks:kadira              added, version 2.15.0
meteorhacks:kadira-binary-deps  added, version 1.3.1
meteorhacks:meteorx             added, version 1.2.0
mongo-livedata                  added, version 1.0.8


meteorhacks:kadira: Performance Monitoring for Meteor
$ meteor update
This project is already at Meteor 1.0.5, the latest release.
Your packages are at their latest compatible versions.
$ meteor list
amqp                0.0.0+ AMQP driver for node
insecure            1.0.3  Allow all database writes by default
meteor-platform     1.2.2  Include a standard set of Meteor packages in your app
meteorhacks:kadira  2.15.0* Performance Monitoring for Meteor
momentjs:moment     2.9.0  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging

**Comment by arunoda** [comment]
This is bad.
Try adding meteor add meteorhacks:kadira@2.20.1

**Comment by javaknight** [comment]
Issues (both mine, and the original reported issue) fixed for me – solved as follows

Explored around and found symlink in packages folder of the project.

Jan  2 16:07 meteorx -> /home/thisisme/.meteorite/packages/meteorx/meteorhacks/meteorx/65d96b9a7a555e766c8d9769a1dc765468817a43

Removed it and was able to update to 2.20.1

Verified the versions
amqp                0.0.0+ AMQP driver for node
insecure            1.0.3  Allow all database writes by default
meteor-platform     1.2.2  Include a standard set of Meteor packages in your app
meteorhacks:kadira  2.20.1  Performance Monitoring for Meteor
momentjs:moment     2.9.0  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging

Deploy from mup and the app itself working just fine now. Thanks
