### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by benjamin79** [meteorhacks/kadira#144]
Not bound to a particular action or a action at all, i get "Converting circular structure to JSON" in  line 50: data: JSON.stringify(payload). Using latest meteor and kadira.

If you need additional info let me know.

**Comment by arunoda** [comment]
Can I have some logs? May be you are sending a cursor from a Meteor method.
Check that also.

**Comment by benjamin79** [comment]
No cursor in a method. The error popped up randomly. Even if the app was left alone.

Sorry for the delay. As is seems, kadira caused multiple problems (mostly IE10/11). So i had to remove it for the time beeing. Our app is still in development. So it's propably the best to integrate kadira again in the final stage. I will get back on that issue in a couple off weeks.

**Comment by helfer** [comment]
Just ran into the same issue. It seems that for Collection.findOne Kadira tries to get an object's size (DocSzCache.getSize) by serializing it to JSON, but transformation happens before that. If it results in a circular structure, Kadira fails and the error causes the whole request to fail.

**Comment by helfer** [comment]
@arunoda This issue causes Kadira to crash my application, which is a big no-no for a package that's just supposed to collect metrics. I had to remove it from my project until this issue is fixed. If it simply caught the error, it would be good enough for me.

**Comment by veered** [comment]
This is still an issue for me. Pretty much a show-stopper unless I fork the package or this is fixed.

**Comment by taind-designveloper** [comment]
sam issue:
Exception while invoking method 'login' TypeError: Converting circular structure to JSON
[54.175.175.172]     at Object.stringify (native)
[54.175.175.172]     at Object.stringify (/bundle/bundle/programs/server/npm/node_modules/meteor/ecmascript-runtime/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/es6.symbol.js:127:21)
[54.175.175.172]     at [object Object].DocSzCache.getSize (packages/meteorhacks_kadira.js:2184:39)
[54.175.175.172]     at Cursor.cursorProto.(anonymous function) (packages/meteorhacks_kadira.js:3392:45)
[54.175.175.172]     at Cursor.kadira_Cursor_fetch [as fetch] (packages/meteorhacks_kadira.js:3738:32)
[54.175.175.172]     at MongoConnection.findOne (packages/mongo/mongo_driver.js:776:56)
[54.175.175.172]     at [object Object].findOne (packages/mongo/collection.js:316:29)
[54.175.175.172]     at AccountsServer.Ap.updateOrCreateUserFromExternalService (packages/accounts-base/accounts_server.js:1353:25)
[54.175.175.172]     at [object Object].Package (packages/accounts-oauth.js:133:21)
[54.175.175.172]     at packages/accounts-base/accounts_server.js:464:32

**Comment by millerone** [comment]
Same issue here.
I get: 

> TypeError: Converting circular structure to JSON
>     at Object.stringify (native)
>     at Object.stringify (C:\Users\miller\AppData\Local\.meteor\packages\ecmascript-runtime\0.3.12\npm\node_modules\meteor-ecmascript-runtime\node_modules\core-js\modules\es6.symbol.js:127:21)
>     at [object Object].DocSzCache.getSize (packages/meteorhacks_kadira/lib/docsize_cache.js:41:1)
>     at Cursor.cursorProto.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:172:1)
>     at Cursor.kadira_Cursor_fetch [as fetch] (packages/meteorhacks_kadira/lib/hijack/set_labels.js:65:1)
>     at MongoConnection.findOne (packages/mongo/mongo_driver.js:811:56)
>     at [object Object].findOne (packages/mongo/collection.js:337:29)
>     at AccountsServer.Accounts._findUserByQuery (packages/accounts-password/password_server.js:99:25)
>     at [object Object].<anonymous> (packages/accounts-password/password_server.js:256:23)
>     at packages/accounts-base/accounts_server.js:470:32

If you need other info i use:
- win10
- Meteor 1.4.0.1

**Comment by namirsab** [comment]
@arunoda same issue here. And we are paying a Kadira subscription.
Any clue?

**Comment by arunoda** [comment]
Will be fixing this by today.

**Comment by xyx2011** [comment]
this issue still exist:

`TypeError: Converting circular structure to JSON
W20170424-13:22:48.272(-7)? (STDERR)     at Object.stringify (native)
W20170424-13:22:48.273(-7)? (STDERR)     at Object.stringify (/Users/user/.meteor/packages/ecmascript-runtime/.0.3.15.1oeyzi2++os+web.browser+web.cordova/npm/node_modules/core-js/modules/es6.symbol.js:224:23)
W20170424-13:22:48.273(-7)? (STDERR)     at stringify (/Users/user/.meteor/packages/meteorhacks_kadira/.2.30.3.ouj1cz++os+web.browser+web.cordova/npm/node_modules/core-js/library/fn/json/stringify.js:4:26)
W20170424-13:22:48.273(-7)? (STDERR)     at Kadira.sendData (/Users/user/.meteor/packages/meteorhacks_kadira/.2.30.3.ouj1cz++os+web.browser+web.cordova/npm/node_modules/kadira-core/dist/index.js:145:42)
W20170424-13:22:48.273(-7)? (STDERR)     at packages/meteorhacks_kadira.js:2449:20
`
