### ISSUE TITLE
Server crash: _.pick

### ISSUE THREAD

**Issue by lorensr** [meteorhacks/kadira#175]
Perhaps it's trying to `pick` from something that it can't access?

```
I20150724-19:01:31.897(-4)? TypeError: Cannot use 'in' operator to search for 'message' in illegal access
I20150724-19:01:31.897(-4)?     at packages/underscore/underscore.js:860:1
I20150724-19:01:31.897(-4)?     at Array.forEach (native)
I20150724-19:01:31.897(-4)?     at _.each._.forEach (packages/underscore/underscore.js:105:1)
I20150724-19:01:31.897(-4)?     at Function._.pick (packages/underscore/underscore.js:859:1)
I20150724-19:01:31.897(-4)?     at [object Object].sessionProto.send (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:107:1)
I20150724-19:01:31.897(-4)?     at [object Object].kadira_Session_send [as send] (packages/meteorhacks:kadira/lib/hijack/set_labels.js:5:1)
I20150724-19:01:31.897(-4)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:666:1)
I20150724-19:01:31.897(-4)?     at packages/meteorhacks:kadira/lib/hijack/wrap_session.js:50:1
I20150724-19:01:31.897(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150724-19:01:31.897(-4)?     at [object Object].sessionProto.protocol_handlers.method (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:49:1)
I20150724-19:01:31.897(-4)?     at packages/ddp/livedata_server.js:546:1
```

**Comment by arunoda** [comment]
Hmm. What's the Meteor version related to this?
Is it possible to have some kind of reproducible code?

This happens when you throw an "string" from your app rather than an Error
Object.
I can do a fix, but interested to find the root for this issue.

**Comment by lorensr** [comment]
```
$ g kadira .meteor/versions 
.meteor/versions:70:meteorhacks:kadira@2.22.0
$ m --version
Meteor 1.1.0.2
```
Not sure where a string is being thrown, but thanks!

**Comment by arunoda** [comment]
Okay. I'll do the fix and notify you.

**Comment by lorensr** [comment]
Maybe could be
```
Kadira.errors.addFilter (errorType, message, error) ->
  console.log error?.stack
```

**Comment by arunoda** [comment]
Hmm. That could be.

**Comment by arunoda** [comment]
Did a potential fix. Update to latest version.
