### ISSUE TITLE
WaitTimeBuilder.register errors

### ISSUE THREAD

**Issue by dpankros** [meteorhacks/kadira#194]
Meteor version: 1.2.0.2
meteorhacks:kadira version 2.11.11
meteorhacks:kadira-binary-deps version 1.2.1

without the kaira package added, I get no errors.
WITH the kadia package added (and a proper Kadira.connect call in my code), I get the following errors when loading a page:
```
Kadira: successfully authenticated
Internal exception while processing message { msg: 'sub',
  id: 'HYjbr4iBQJr8kH8Je',
  name: 'meteor.loginServiceConfiguration',
  params: [] } Object  has no method 'map' TypeError: Object  has no method 'map'
    at [object Object].WaitTimeBuilder.register (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:433:1)
    at [object Object].sessionProto.processMessage (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:2269:1)
    at SockJSConnection.<anonymous> (livedata_server.js:1365:31)
    at SockJSConnection.emit (events.js:95:17)
    at Session.didMessage (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/transport.js:246:25)
    at WebSocketReceiver.didMessage (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:99:40)
    at [object Object].<anonymous> (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:70:24)
    at [object Object].emit (events.js:95:17)
    at [object Object].EventTarget.dispatchEvent (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
    at [object Object].instance._receiveMessage (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
Internal exception while processing message { msg: 'sub',
  id: 'D4p5TCkD5yi2yaR3F',
  name: '_roles',
  params: [] } Object  has no method 'map' TypeError: Object  has no method 'map'
    at [object Object].WaitTimeBuilder.register (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:433:1)
    at [object Object].sessionProto.processMessage (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:2269:1)
    at SockJSConnection.<anonymous> (livedata_server.js:1365:31)
    at SockJSConnection.emit (events.js:95:17)
    at Session.didMessage (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/transport.js:246:25)
    at WebSocketReceiver.didMessage (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:99:40)
    at [object Object].<anonymous> (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:70:24)
    at [object Object].emit (events.js:95:17)
    at [object Object].EventTarget.dispatchEvent (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
    at [object Object].instance._receiveMessage (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
Internal exception while processing message { msg: 'sub',
  id: 'dDGNjwwY629WXmp6s',
  name: 'meteor_autoupdate_clientVersions',
  params: [] } Object  has no method 'map' TypeError: Object  has no method 'map'
    at [object Object].WaitTimeBuilder.register (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:433:1)
    at [object Object].sessionProto.processMessage (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:2269:1)
    at SockJSConnection.<anonymous> (livedata_server.js:1365:31)
    at SockJSConnection.emit (events.js:95:17)
    at Session.didMessage (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/transport.js:246:25)
    at WebSocketReceiver.didMessage (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:99:40)
    at [object Object].<anonymous> (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:70:24)
    at [object Object].emit (events.js:95:17)
    at [object Object].EventTarget.dispatchEvent (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
    at [object Object].instance._receiveMessage (/Users/hidden/.meteor/packages/ddp-server/.1.2.1.vjho5h++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
``` 

Because none of my code is even in the stack, I'm not sure where to even start with this.  Are these proper Kadira errors or just Kadira catching thrown exceptions?  I'm guessing the former (because I don't see other packages in the stacks either), but it's sufficiently bizarre that I'm not taking anything for granted right now.

**Comment by arunoda** [comment]
This is because of your outdated Kadira package.
Try to update it to the latest version. That'll fix it.

**Comment by dpankros** [comment]
That seems to have corrected it.  Sorry for the false report, but thanks for your help.  I didn't notice that another component was holding back the version of kadira to 2.11.11.
