### ISSUE TITLE
Error: Match error: Failed Match.OneOf or Match.Optional validation

### ISSUE THREAD

**Issue by gabrielpugliese-luizalabs** [meteorhacks/kadira#198]
Just created a brand new Meteor@1.2.1 project, added Kadira@2.26.1 and it is raising on server console:

```
W20151106-17:21:47.831(-2)? (STDERR) /Users/gabrielpugliese/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151106-17:20:58.525(-2)? (STDERR)                                            throw(ex);
W20151106-17:20:58.525(-2)? (STDERR)                                                  ^
W20151106-17:20:58.690(-2)? (STDERR) Error: Match error: Failed Match.OneOf or Match.Optional validation
W20151106-17:20:58.690(-2)? (STDERR)     at check (packages/check/match.js:33:1)
W20151106-17:20:58.691(-2)? (STDERR)     at [object Object]._.extend._getFindOptions (packages/mongo/collection.js:248:1)
W20151106-17:20:58.691(-2)? (STDERR)     at [object Object]._.extend.find (packages/mongo/collection.js:284:1)
W20151106-17:20:58.691(-2)? (STDERR)     at exposePollingDriver (packages/meteorhacks_meteorx/lib/mongo-livedata.js:24:1)
W20151106-17:20:58.691(-2)? (STDERR)     at exposeMongoLivedata (packages/meteorhacks_meteorx/lib/mongo-livedata.js:11:1)
W20151106-17:20:58.691(-2)? (STDERR)     at packages/meteorhacks_meteorx/lib/server.js:22:1
W20151106-17:20:58.691(-2)? (STDERR)     at runWithAFiber (packages/meteorhacks_meteorx/lib/server.js:33:1)
W20151106-17:20:58.691(-2)? (STDERR)     at Package (packages/meteorhacks_meteorx/lib/server.js:21:1)
W20151106-17:20:58.692(-2)? (STDERR)     at /Users/gabrielpugliese/Workspace/voce-noel-front/.meteor/local/build/programs/server/boot.js:249:5
```

Works fine if I remove the package. Any idea?

**Comment by gabrielpugliese-luizalabs** [comment]
Version `2.25.0` is working

**Comment by gabrielpugliese-luizalabs** [comment]
False alarm. The app starts, but I get those errors:
```
I20151106-17:30:37.026(-2)? Internal exception while processing message { msg: 'method',
I20151106-17:30:37.029(-2)?   method: 'login',
I20151106-17:30:37.029(-2)?   params: [ { resume: 'TLGx4IIcBGKbKEini_llILA3p-zMWvTKWVRsvC6F8ni' } ],
I20151106-17:30:37.030(-2)?   id: '1' } Object  has no method 'map' TypeError: Object  has no method 'map'
I20151106-17:30:37.030(-2)?     at [object Object].sessionProto.processMessage (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:1691:1)
I20151106-17:30:37.030(-2)?     at SockJSConnection.<anonymous> (livedata_server.js:1371:31)
I20151106-17:30:37.030(-2)?     at SockJSConnection.emit (events.js:95:17)
I20151106-17:30:37.030(-2)?     at Session.didMessage (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/transport.js:246:25)
I20151106-17:30:37.030(-2)?     at WebSocketReceiver.didMessage (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:99:40)
I20151106-17:30:37.030(-2)?     at [object Object].<anonymous> (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:70:24)
I20151106-17:30:37.030(-2)?     at [object Object].emit (events.js:95:17)
I20151106-17:30:37.031(-2)?     at [object Object].EventTarget.dispatchEvent (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
I20151106-17:30:37.031(-2)?     at [object Object].instance._receiveMessage (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
I20151106-17:30:37.031(-2)?     at [object Object].<anonymous> (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
I20151106-17:30:37.031(-2)? Internal exception while processing message { msg: 'sub',
I20151106-17:30:37.031(-2)?   id: 'uFZmJe3xdpcN3a4GR',
I20151106-17:30:37.031(-2)?   name: 'meteor.loginServiceConfiguration',
I20151106-17:30:37.031(-2)?   params: [],
I20151106-17:30:37.031(-2)?   route: null } Object  has no method 'map' TypeError: Object  has no method 'map'
I20151106-17:30:37.032(-2)?     at [object Object].sessionProto.processMessage (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:1691:1)
I20151106-17:30:37.032(-2)?     at SockJSConnection.<anonymous> (livedata_server.js:1371:31)
I20151106-17:30:37.032(-2)?     at SockJSConnection.emit (events.js:95:17)
I20151106-17:30:37.032(-2)?     at Session.didMessage (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/transport.js:246:25)
I20151106-17:30:37.032(-2)?     at WebSocketReceiver.didMessage (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:99:40)
I20151106-17:30:37.033(-2)?     at [object Object].<anonymous> (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:70:24)
I20151106-17:30:37.033(-2)?     at [object Object].emit (events.js:95:17)
I20151106-17:30:37.033(-2)?     at [object Object].EventTarget.dispatchEvent (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
I20151106-17:30:37.034(-2)?     at [object Object].instance._receiveMessage (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
I20151106-17:30:37.034(-2)?     at [object Object].<anonymous> (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
I20151106-17:30:37.047(-2)? Internal exception while processing message { msg: 'sub',
I20151106-17:30:37.048(-2)?   id: '5PwPd9G22et2ejfWN',
I20151106-17:30:37.048(-2)?   name: 'meteor_autoupdate_clientVersions',
I20151106-17:30:37.048(-2)?   params: [],
I20151106-17:30:37.048(-2)?   route: null } Object  has no method 'map' TypeError: Object  has no method 'map'
I20151106-17:30:37.048(-2)?     at [object Object].sessionProto.processMessage (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:1691:1)
I20151106-17:30:37.048(-2)?     at SockJSConnection.<anonymous> (livedata_server.js:1371:31)
I20151106-17:30:37.048(-2)?     at SockJSConnection.emit (events.js:95:17)
I20151106-17:30:37.048(-2)?     at Session.didMessage (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/transport.js:246:25)
I20151106-17:30:37.049(-2)?     at WebSocketReceiver.didMessage (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:99:40)
I20151106-17:30:37.049(-2)?     at [object Object].<anonymous> (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/lib/trans-websocket.js:70:24)
I20151106-17:30:37.049(-2)?     at [object Object].emit (events.js:95:17)
I20151106-17:30:37.049(-2)?     at [object Object].EventTarget.dispatchEvent (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
I20151106-17:30:37.049(-2)?     at [object Object].instance._receiveMessage (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
I20151106-17:30:37.049(-2)?     at [object Object].<anonymous> (/Users/gabrielpugliese/.meteor/packages/ddp-server/.1.2.2.oxt4i1++os+web.browser+web.cordova/npm/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
```

**Comment by gabrielpugliese-luizalabs** [comment]
Version `2.24.1` raises the same error as `2.26.1` on startup.

**Comment by gabrielpugliese-luizalabs** [comment]
Maybe due to the `Number` constructor and es6?

**Comment by gabrielpugliese-luizalabs** [comment]
That's it. I was using `babel/polyfill` with webpack :)
