### ISSUE TITLE
Kadira conflicting with Migrations

### ISSUE THREAD

**Issue by dfischer** [meteorhacks/kadira#203]
While trying to run migrations it seems that Kadira is conflicting with Perocolate Migrations:

```
W20151214-11:57:07.570(-8)? (STDERR) /Users/daniel/.meteor/packages/meteor-tool/.1.1.9.63n1p1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151214-11:57:07.570(-8)? (STDERR) 						throw(ex);
W20151214-11:57:07.570(-8)? (STDERR) 						      ^
W20151214-11:57:07.609(-8)? (STDERR) TypeError: Cannot read property 'upsert' of undefined
W20151214-11:57:07.609(-8)? (STDERR)     at [object Object].mongoConnectionProto.(anonymous function) [as update] (packages/meteorhacks_kadira/lib/hijack/db.js:73:1)
W20151214-11:57:07.609(-8)? (STDERR)     at OptimizedApply (packages/meteorhacks_kadira/lib/utils.js:31:1)
W20151214-11:57:07.609(-8)? (STDERR)     at Object.ret.(anonymous function) [as update] (packages/meteorhacks_kadira/lib/hijack/db.js:20:1)
W20151214-11:57:07.609(-8)? (STDERR)     at 11_tickets_created_by.js:8:19
W20151214-11:57:07.609(-8)? (STDERR)     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1022:1)
W20151214-11:57:07.609(-8)? (STDERR)     at [object Object].Cursor.(anonymous function) (packages/mongo/mongo_driver.js:869:1)
W20151214-11:57:07.609(-8)? (STDERR)     at [object Object].cursorProto.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:126:1)
W20151214-11:57:07.609(-8)? (STDERR)     at [object Object].kadira_Cursor_forEach [as forEach] (packages/meteorhacks_kadira/lib/hijack/set_labels.js:63:1)
W20151214-11:57:07.609(-8)? (STDERR)     at Object.Migrations.add.up (11_tickets_created_by.js:5:22)
W20151214-11:57:07.609(-8)? (STDERR)     at migrate (packages/percolate_migrations/migrations_server.js:203:1)
W20151214-11:57:07.609(-8)? (STDERR)     at Object.Migrations._migrateTo (packages/percolate_migrations/migrations_server.js:223:1)
W20151214-11:57:07.609(-8)? (STDERR)     at Object.Migrations.migrateTo (packages/percolate_migrations/migrations_server.js:139:1)
W20151214-11:57:07.610(-8)? (STDERR)     at Migrations.add (packages/percolate_migrations/migrations_server.js:98:1)
W20151214-11:57:07.610(-8)? (STDERR)     at /Users/daniel/Code/project/project-universe/asteroid/.meteor/local/build/programs/server/boot.js:249:5
```

I think because of a wrapper around mongo driver... thoughts?

---

If I remove kadira it works.

**Comment by dfischer** [comment]
Changing load order fixed it...
