### ISSUE TITLE
Type Error crashing server

### ISSUE THREAD

**Issue by structuresound** [meteorhacks/kadira#207]
This is intermittent, I'll update if I narrow down the cause.

```
TypeError: Cannot read property 'statusCode' of undefined
W20160120-13:16:33.447(-8)? (STDERR)     at Request._callback (/Users/leif/.meteor/packages/meteorhacks_kadira/.2.27.0.1egho0p++os+web.browser+web.cordova/npm/node_modules/kadira-core/dist/index.js:175:20)
W20160120-13:16:33.447(-8)? (STDERR)     at self.callback (/Users/leif/.meteor/packages/meteorhacks_kadira/.2.27.0.1egho0p++os+web.browser+web.cordova/npm/node_modules/kadira-core/node_modules/request/request.js:198:22)
W20160120-13:16:33.447(-8)? (STDERR)     at Request.emit (events.js:95:17)
W20160120-13:16:33.447(-8)? (STDERR)     at Request.onRequestError (/Users/leif/.meteor/packages/meteorhacks_kadira/.2.27.0.1egho0p++os+web.browser+web.cordova/npm/node_modules/kadira-core/node_modules/request/request.js:820:8)
W20160120-13:16:33.447(-8)? (STDERR)     at ClientRequest.emit (events.js:95:17)
W20160120-13:16:33.447(-8)? (STDERR)     at CleartextStream.socketErrorListener (http.js:1548:9)
W20160120-13:16:33.447(-8)? (STDERR)     at CleartextStream.emit (events.js:95:17)
W20160120-13:16:33.448(-8)? (STDERR)     at Socket.onerror (tls.js:1456:17)
W20160120-13:16:33.448(-8)? (STDERR)     at Socket.emit (events.js:117:20)
W20160120-13:16:33.448(-8)? (STDERR)     at net.js:441:14
W20160120-13:16:33.448(-8)? (STDERR)     at process._tickDomainCallback (node.js:492:13)
```

**Comment by structuresound** [comment]
wait looks like this has been addressed here:

https://github.com/kadirahq/kadira-core/commit/c61e57d35a8a5c68af41fa6578e8ff58988613a2

probably just hasn't propagated to nom yet?

**Comment by structuresound** [comment]
assuming this is fixed in:
```
meteorhacks:kadira@2.27.2
```
