### ISSUE TITLE
Adding kadira causes ringcentral sdk to crash

### ISSUE THREAD

**Issue by shantanuthatte** [meteorhacks/kadira#225]
After adding `meteorhacks:kadira` i get the following error:
```
I20160323-16:38:21.325(-4)? { [Error: native promise missing, set Fetch.Promise to your favorite alternative]
I20160323-16:38:21.326(-4)?   apiResponse:
I20160323-16:38:21.327(-4)?    { _request:
I20160323-16:38:21.327(-4)?       { method: 'POST',
I20160323-16:38:21.328(-4)?         headers: [Object],
I20160323-16:38:21.328(-4)?         body: 'access_token_ttl=null&refresh_token_ttl=36000&grant_type=password&username=<censored>&password=<censored>&extension=<censored>',
I20160323-16:38:21.328(-4)?         url: 'https://platform.devtest.ringcentral.com/restapi/oauth/token',
I20160323-16:38:21.328(-4)?         follow: 20,
I20160323-16:38:21.328(-4)?         counter: 0,
I20160323-16:38:21.329(-4)?         timeout: 0,
I20160323-16:38:21.329(-4)?         compress: true,
I20160323-16:38:21.329(-4)?         size: 0,
I20160323-16:38:21.329(-4)?         agent: undefined,
I20160323-16:38:21.330(-4)?         protocol: 'https:',
I20160323-16:38:21.330(-4)?         hostname: 'platform.devtest.ringcentral.com',
I20160323-16:38:21.330(-4)?         port: null,
I20160323-16:38:21.330(-4)?         path: '/restapi/oauth/token',
I20160323-16:38:21.330(-4)?         auth: null,
I20160323-16:38:21.331(-4)?         originalBody: 'access_token_ttl=null&refresh_token_ttl=36000&grant_type=password&username=<censored>&password=<censored>&extension=<censored>' },
I20160323-16:38:21.331(-4)?      _response: undefined,
I20160323-16:38:21.331(-4)?      _text: undefined,
I20160323-16:38:21.331(-4)?      _json: null,
I20160323-16:38:21.332(-4)?      _multipart: [] },
I20160323-16:38:21.332(-4)?   originalMessage: 'native promise missing, set Fetch.Promise to your favorite alternative' }
I20160323-16:38:21.333(-4)? Kadira: completed instrumenting the app
I20160323-16:38:21.333(-4)? Kadira: Successfully connected
```

Removing kadira solves the problem. Any ideas as to what may be going wrong?

**Comment by csiszi** [comment]
I'm getting the same error without ringcentral as well:

```
W20160418-00:36:47.821(2)? (STDERR) Error: native promise missing, set Fetch.Promise to your favorite alternative
W20160418-00:36:47.822(2)? (STDERR)     at new Fetch (/Users/csiszi/.meteor/packages/meteorhacks_kadira/.2.28.5.1fvi1kw++os+web.browser+web.cordova/npm/node_modules/kadira-core/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:36:9)
W20160418-00:36:47.822(2)? (STDERR)     at Fetch (/Users/csiszi/.meteor/packages/meteorhacks_kadira/.2.28.5.1fvi1kw++os+web.browser+web.cordova/npm/node_modules/kadira-core/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:32:10)
W20160418-00:36:47.822(2)? (STDERR)     at module.exports (/Users/csiszi/.meteor/packages/meteorhacks_kadira/.2.28.5.1fvi1kw++os+web.browser+web.cordova/npm/node_modules/kadira-core/node_modules/isomorphic-fetch/fetch-npm-node.js:8:19)
W20160418-00:36:47.823(2)? (STDERR)     at [object Object].run (lib/collections/guests.js:778:5)
W20160418-00:36:47.823(2)? (STDERR)     at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:87:12)
W20160418-00:36:47.823(2)? (STDERR)     at [object Object].ValidatedMethod.connection.methods._connection$methods.(anonymous function) (packages/mdg:validated-method/validated-method.js:37:23)
W20160418-00:36:47.824(2)? (STDERR)     at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira.js:2731:30)
W20160418-00:36:47.824(2)? (STDERR)     at packages/check.js:211:16
W20160418-00:36:47.824(2)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
W20160418-00:36:47.825(2)? (STDERR)     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check.js:210:41)
```
