### ISSUE TITLE
Error: name is not a string. perhaps the file extension isn't .rjs?

### ISSUE THREAD

**Issue by kaushik1979** [meteorhacks/kadira#226]
Getting the following error - 

`
=> Started MongoDB.                           
W20160409-07:57:02.090(-4)? (STDERR)          
W20160409-07:57:02.091(-4)? (STDERR) /Users/priyankasharma/.meteor/packages/meteor-tool/.1.3.1.1vrtdxs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160409-07:57:02.092(-4)? (STDERR) 						throw(ex);
W20160409-07:57:02.092(-4)? (STDERR) 						      ^
W20160409-07:57:02.092(-4)? (STDERR) Error: name is not a string. perhaps the file extension isn't .rjs?
W20160409-07:57:02.092(-4)? (STDERR)     at Object.define (packages/mrt_require.js:99:13)
W20160409-07:57:02.092(-4)? (STDERR)     at Object.<anonymous> (/Users/priyankasharma/.meteor/packages/meteorhacks_kadira/.2.28.5.tln84w++os+web.browser+web.cordova/npm/node_modules/kadira-core/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/json-schema/lib/validate.js:17:1)
W20160409-07:57:02.092(-4)? (STDERR)     at Module._compile (module.js:456:26)
W20160409-07:57:02.092(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160409-07:57:02.092(-4)? (STDERR)     at Module.load (module.js:356:32)
W20160409-07:57:02.092(-4)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160409-07:57:02.092(-4)? (STDERR)     at Module.require (module.js:364:17)
W20160409-07:57:02.093(-4)? (STDERR)     at require (module.js:380:17)
W20160409-07:57:02.093(-4)? (STDERR)     at Object.<anonymous> (/Users/priyankasharma/.meteor/packages/meteorhacks_kadira/.2.28.5.tln84w++os+web.browser+web.cordova/npm/node_modules/kadira-core/node_modules/request/node_modules/http-signature/node_modules/jsprim/lib/jsprim.js:10:22)
W20160409-07:57:02.093(-4)? (STDERR)     at Module._compile (module.js:456:26)
=> Exited with code: 8
W20160409-07:57:06.780(-4)? (STDERR)          
W20160409-07:57:06.781(-4)? (STDERR) /Users/priyankasharma/.meteor/packages/meteor-tool/.1.3.1.1vrtdxs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160409-07:57:06.781(-4)? (STDERR) 						throw(ex);
W20160409-07:57:06.781(-4)? (STDERR) 						      ^
W20160409-07:57:06.783(-4)? (STDERR) Error: name is not a string. perhaps the file extension isn't .rjs?
W20160409-07:57:06.784(-4)? (STDERR)     at Object.define (packages/mrt_require.js:99:13)
W20160409-07:57:06.784(-4)? (STDERR)     at Object.<anonymous> (/Users/priyankasharma/.meteor/packages/meteorhacks_kadira/.2.28.5.tln84w++os+web.browser+web.cordova/npm/node_modules/kadira-core/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/json-schema/lib/validate.js:17:1)
W20160409-07:57:06.784(-4)? (STDERR)     at Module._compile (module.js:456:26)
W20160409-07:57:06.784(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160409-07:57:06.784(-4)? (STDERR)     at Module.load (module.js:356:32)
W20160409-07:57:06.784(-4)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160409-07:57:06.784(-4)? (STDERR)     at Module.require (module.js:364:17)
W20160409-07:57:06.785(-4)? (STDERR)     at require (module.js:380:17)
W20160409-07:57:06.785(-4)? (STDERR)     at Object.<anonymous> (/Users/priyankasharma/.meteor/packages/meteorhacks_kadira/.2.28.5.tln84w++os+web.browser+web.cordova/npm/node_modules/kadira-core/node_modules/request/node_modules/http-signature/node_modules/jsprim/lib/jsprim.js:10:22)
W20160409-07:57:06.785(-4)? (STDERR)     at Module._compile (module.js:456:26)
=> Exited with code: 8
W20160409-07:57:11.888(-4)? (STDERR)          
W20160409-07:57:11.888(-4)? (STDERR) /Users/priyankasharma/.meteor/packages/meteor-tool/.1.3.1.1vrtdxs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160409-07:57:11.888(-4)? (STDERR) 						throw(ex);
W20160409-07:57:11.889(-4)? (STDERR) 						      ^
W20160409-07:57:11.891(-4)? (STDERR) Error: name is not a string. perhaps the file extension isn't .rjs?
W20160409-07:57:11.891(-4)? (STDERR)     at Object.define (packages/mrt_require.js:99:13)
W20160409-07:57:11.891(-4)? (STDERR)     at Object.<anonymous> (/Users/priyankasharma/.meteor/packages/meteorhacks_kadira/.2.28.5.tln84w++os+web.browser+web.cordova/npm/node_modules/kadira-core/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/json-schema/lib/validate.js:17:1)
W20160409-07:57:11.891(-4)? (STDERR)     at Module._compile (module.js:456:26)
W20160409-07:57:11.891(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160409-07:57:11.891(-4)? (STDERR)     at Module.load (module.js:356:32)
W20160409-07:57:11.891(-4)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160409-07:57:11.891(-4)? (STDERR)     at Module.require (module.js:364:17)
W20160409-07:57:11.892(-4)? (STDERR)     at require (module.js:380:17)
W20160409-07:57:11.892(-4)? (STDERR)     at Object.<anonymous> (/Users/priyankasharma/.meteor/packages/meteorhacks_kadira/.2.28.5.tln84w++os+web.browser+web.cordova/npm/node_modules/kadira-core/node_modules/request/node_modules/http-signature/node_modules/jsprim/lib/jsprim.js:10:22)
W20160409-07:57:11.892(-4)? (STDERR)     at Module._compile (module.js:456:26)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
`

Here are my Meteor dependencies - 

`
accounts-facebook                   1.0.8  Login service for Facebook accounts
accounts-google                     1.0.8  Login service for Google accounts
accounts-password                   1.1.7  Password support for accounts
aldeed:autoform                     5.8.1  Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:autoform-bs-datetimepicker   1.0.6  Custom bootstrap-datetimepicker input type with timezone support for AutoForm
aldeed:collection2                  2.9.1  Automatic validation of insert and update operations on the client and server.
andruschka:bootstrap-image-gallery  0.0.5  Blueimp's bootstrap image gallery
blaze-html-templates                1.0.3  Compile HTML templates into reactive UI with Meteor Blaze
cfs:filesystem                      0.1.2  Filesystem storage adapter for CollectionFS
cfs:graphicsmagick                  0.0.18  Adds `gm` to scope with the ability to perform GraphicsMagick or ImageMagick manipulation
cfs:gridfs                          0.0.33  GridFS storage adapter for CollectionFS
cfs:standard-packages               0.5.9  Filesystem for Meteor, collectionFS
check                               1.1.3  Check whether a value matches a pattern
ejson                               1.0.10  Extended and Extensible JSON library
email                               1.0.11  Send email messages
hilios:jquery.countdown             2.0.4  The Final Countdown plugin for jQuery
houston:admin                       2.0.7  A zero-config Meteor Admin
http                                1.1.4  Make HTTP calls to remote servers
ian:accounts-ui-bootstrap-3         1.2.89  Bootstrap-styled accounts-ui with multi-language support.
iron:router                         1.0.12  Routing specifically designed for Meteor
jparker:crypto-aes                  0.1.0  AES Package for CryptoJS, standard secure algorithms
jparker:crypto-md5                  0.1.1  MD5 algorithm for CryptoJS, standard secure algorithms
jparker:gravatar                    0.4.1  Simple package to use gravatar images
jquery                              1.11.7  Manipulate the DOM using CSS selectors
logging                             1.0.11  Logging facility.
long:google-contacts                0.2.0  Google-Contacts package
maazalik:highcharts                 0.4.0  HighCharts for Meteor, with an easy to use helper to get you started!
manuelschoebel:wait-on-lib          0.3.0  Use Meteor Iron-Routers waitOn to load external javascript
meteor-base                         1.0.3  Packages that every Meteor app needs
meteorhacks:cluster                 1.6.9  Clustering solution for Meteor with load balancing and service discovery.
meteorhacks:fast-render             2.13.0  Render your app before the DDP connection even comes alive - magic?
meteorhacks:kadira                  2.28.5  Performance Monitoring for Meteor
meteorhacks:npm                     1.5.0  Use npm modules with your Meteor App
meteorhacks:search-source           1.4.2  Reactive Data Source for Search
miguelalarcos:afwrap-xautocomplete  0.3.1  wrap over xautocomplete so it works ok with autoform
mikael:accounts-merge               0.0.11  Multiple login services for Meteor accounts
mizzao:jquery-ui                    1.11.4  Simple lightweight pull-in for jQuery UI in Meteor
mizzao:user-status                  0.6.6  User connection and idle state tracking for Meteor
mobile-experience                   1.0.3  Packages for a great mobile user experience
momentjs:moment                     2.12.0  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                               1.1.6  Adaptor for using MongoDB and Minimongo over DDP
mrt:ace-embed                       0.0.4  A jQuery & Ace Editor wrapper for meteorite on top of meteor.
mrt:datatables                      0.1.3  DataTable - jQuery plugin for sortable, pagable data
mrt:jqtree                          0.19.0  meteor packaged jqTree (https://github.com/mbraak/jqTree)
mrt:mathjax                         0.6.3  Render math formulas with mathjax
mrt:require                         0.1.0  A very simple implementation of require/define for meteor
npm-container                       1.1.0+ Contains all your npm dependencies
perak:markdown                      1.0.5  GitHub flavored markdown parser for Meteor based on marked.js
pfafman:font-awesome-4              4.4.0_3  Font awesome packaged for meteor
random                              1.0.8  Random number generator and utilities
reactive-dict                       1.1.6  Reactive dictionary
reload                              1.1.7  Reload the page while preserving application state.
semantic:ui-icon                    1.12.3* Semantic UI - Icon: Single component release
service-configuration               1.0.8  Manage the configuration for third-party services
session                             1.1.4  Session variable
simple:katex                        1.1.0  KaTeX 0.4.2 for Meteor
simple:reactive-method              1.0.2  Call methods synchronously inside Tracker.autorun
spacebars                           1.0.10  Handlebars-like template language for Meteor
splendido:accounts-meld             1.3.1  Meteor package to link/meld user accounts registered with the same (verified) email address.
standard-minifier-css               1.0.5  Standard css minifier used with Meteor apps by default.
standard-minifier-js                1.0.5  Standard javascript minifiers used with Meteor apps by default.
tap:i18n                            1.8.0  A comprehensive internationalization solution for Meteor
tracker                             1.0.12  Dependency tracker to allow reactive callbacks
tsega:bootstrap3-datetimepicker     3.1.3_3* Bootstrap 3 DateTime picker from @Eonasdan, packaged for Meteor.js
twbs:bootstrap                      3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.
wylio:mandrill                      0.3.0* Send email via Mandrill's send-template.json
yogiben:pretty-email                0.0.7  Send pretty emails
yong:meteor-videojs                 1.1.0  Video.js 4.12.5
zimme:active-route                  2.3.2  Active route helpers
`

**Comment by kaushik1979** [comment]
Seems like this is coming from mrt_require.js

`
$ grep -rnw ./ -e "\.rjs"
.//.meteor/local/build/programs/server/packages/mrt_require.js:99:      throw new Error("name is not a string. perhaps the file extension isn't .rjs?");  // 72
.//.meteor/local/build/programs/web.browser/packages/mrt_require.js:99:      throw new Error("name is not a string. perhaps the file extension isn't .rjs?");  // 72  // 80
`
