### ISSUE TITLE
Kadira breaks under the new mongo driver (2.1.18, that will be soon on meteor)

### ISSUE THREAD

**Issue by Fabs** [meteorhacks/kadira#234]
Hey Guys, 

I am working along with the MDG in switching the next version of meteor to the newest possible native mongodb driver. It is not fully integrated on `devel`, but will soon be on the `mongo-3.2` branch. You can see the PR here https://github.com/meteor/meteor/pull/7104

When I was testing in a project kadira broke because of the new driver. 

```
W20160529-17:58:30.183(-3)? (STDERR) /Users/fabs/code/meteor-mongo-3.2/meteor/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160529-17:58:30.183(-3)? (STDERR)            			throw(ex);
W20160529-17:58:30.184(-3)? (STDERR)            			      ^
W20160529-17:58:30.184(-3)? (STDERR) TypeError: Cannot read property 'createDataHandler' of undefined
W20160529-17:58:30.184(-3)? (STDERR)     at setLabels (packages/meteorhacks_kadira/lib/hijack/set_labels.js:10:1)
W20160529-17:58:30.184(-3)? (STDERR)     at packages/meteorhacks_kadira/lib/hijack/instrument.js:33:1
W20160529-17:58:30.184(-3)? (STDERR)     at runWithAFiber (packages/meteorhacks_meteorx/lib/server.js:33:1)
W20160529-17:58:30.184(-3)? (STDERR)     at packages/meteorhacks_meteorx/lib/server.js:26:1
W20160529-17:58:30.185(-3)? (STDERR)     at Array.forEach (/Users/fabs/code/meteor-mongo-3.2/meteor/packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:435:21)
W20160529-17:58:30.185(-3)? (STDERR)     at Package (packages/meteorhacks_meteorx/lib/server.js:25:1)
W20160529-17:58:30.185(-3)? (STDERR)     at /Users/fabs/code/react/board/.meteor/local/build/programs/server/boot.js:290:5
```

The reason is that, even though there is still `MongoInternals.NpmModule` as a backward compatibility feature (the new place where it is expected to be since 1.0.3.2 is `MongoInternals.NpmModules.mongodb.module` the new driver *does not have a Connection property* and thus 

`var originalCreateDataHandler = mongodb.Connection.createDataHandler;`

throws an error.

**Comment by arunoda** [comment]
Thanks @Fabs.
I'll make changes.

**Comment by MechJosh0** [comment]
Still experiencing this problem in v2.29.0. I've removed the package for the time being to be able to use Meteor 1.4-beta-3.

**Comment by arunoda** [comment]
@MechJosh0 check `v2.29.1`.

**Comment by MechJosh0** [comment]
@arunoda I can confirm `v2.29.1` worked for me. Thank you.

**Comment by ankibalyan** [comment]
Can I use `kadira:debug` in my `Meteor 1.4.1.1`,  How can I just fix the same error for now?

**Comment by jaredtmartin** [comment]
Having the same problem, is there a fix?

**Comment by webmagnets** [comment]
+1

**Comment by nelson-uruworks** [comment]
+1

update: v2.30.2 is working for me

**Comment by whuber-work** [comment]
still experiencing the problem for kadira:debug

**Comment by Nullpo** [comment]
I have the same problem here :(

**Comment by rohit-htc** [comment]
W20170320-09:30:12.360(5.5)? (STDERR) 						throw(ex);
W20170320-09:30:12.360(5.5)? (STDERR) 						^
W20170320-09:30:12.360(5.5)? (STDERR) 
W20170320-09:30:12.361(5.5)? (STDERR) TypeError: Cannot read property 'createDataHandler' of undefined
W20170320-09:30:12.361(5.5)? (STDERR)     at setLabels (packages/meteorhacks_kadira.js:3335:53)
W20170320-09:30:12.361(5.5)? (STDERR)     at packages/meteorhacks_kadira.js:2872:5
W20170320-09:30:12.361(5.5)? (STDERR)     at packages/meteorhacks_meteorx.js:190:7
W20170320-09:30:12.362(5.5)? (STDERR)     at Array.forEach (native)
W20170320-09:30:12.362(5.5)? (STDERR)     at packages/meteorhacks_meteorx.js:189:29

Any solution for this?

**Comment by AronVanAmmers** [comment]
I had this issue on `meteorhacks:kadira` v2.23.4 with Meteor 1.4.2.3.

Updating to `meteorhacks:kadira` v2.30.3 with Meteor v1.4.4.2 fixed it for me. The issue is resolved and Kadira works.
