### ISSUE TITLE
Error - Meteor 1.4.1.3

### ISSUE THREAD

**Issue by s-devaney** [meteorhacks/kadira#254]
```
TypeError: Cannot read property 'createDataHandler' of undefined
at setLabels (meteor://�app/packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:3303:1)
at meteor://�app/packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:2840:1
at meteor://�app/packages/meteorhacks_meteorx/packages/meteorhacks_meteorx.js:169:1
at Array.forEach (native)
at meteor://�app/packages/meteorhacks_meteorx/packages/meteorhacks_meteorx.js:168:1
```

During start up

**Comment by arunoda** [comment]
Could you update `meteorhacks:kadira` to the latest?

**Comment by olearycrew** [comment]
Same problem:

TypeError: Cannot read property 'createDataHandler' of undefined
W20170223-14:07:20.742(-5)? (STDERR)     at setLabels (packages/meteorhacks_kadira.js:3335:53)
 at packages/meteorhacks_kadira.js:2872:5
 at packages/meteorhacks_meteorx.js:190:7
 at Array.forEach (native)
 at packages/meteorhacks_meteorx.js:189:29 

With meteor 1.4.2.6 and 

kadira:debug         added, version 3.2.2     
kadira:runtime-dev   added, version 0.0.1
meteorhacks:kadira   added, version 2.23.4
meteorhacks:meteorx  added, version 1.3.1

**Comment by arunoda** [comment]
@brendano86 remove `kadira:debug` and update `meteorhacks:kadira` to the latest.

**Comment by vmdao** [comment]
Error same me. And i change install to  meteorhacks:kadira, has not error. But http://debug.kadiraio.com/debug show info `Your app is using an older version of `kadira:debug` or it doesn't have `kadira:debug` package. Install the latest version of `kadira:debug`.`

**Comment by joerex** [comment]
I'm getting the same as @brendano86 and @vmdao on Meteor 1.4.1.2 and 1.5.0-beta.13.

**Comment by maitrid** [comment]
i have the same issue. my Meteor version is 1.4.2.7
