### ISSUE TITLE
Errors prevented bundling: While building package `kadira`

### ISSUE THREAD

**Issue by devzsolt** [meteorhacks/kadira#8]
Could you please help me fix this build issue? I try to build it in a Docker container on Ubuntu 14.04
Please let me know if you need more info. Thanks!

module.js:340
    throw err;
          ^
Error: Cannot find module '/root/.meteorite/packages/kadira/meteorhacks/kadira/fa9a6446f6efb576953f99c01c03474f56f3852e/.npm/package-new-yekpyo/node_modules/usage/node_modules/.bin/node-gyp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR! usage@0.4.4 install: `./build.sh`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the usage@0.4.4 install script.
npm ERR! This is most likely a problem with the usage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./build.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls usage
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/root/.meteor/tools/858c88b520/bin/node" "/root/.meteor/tools/858c88b520/bin/npm" "install" "usage@0.4.4"
npm ERR! cwd /root/.meteorite/packages/kadira/meteorhacks/kadira/fa9a6446f6efb576953f99c01c03474f56f3852e/.npm/package-new-yekpyo
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/.meteorite/packages/kadira/meteorhacks/kadira/fa9a6446f6efb576953f99c01c03474f56f3852e/.npm/package-new-yekpyo/npm-debug.log
npm ERR! not ok code 0

Errors prevented bundling:
While building package `kadira`:
error: couldn't install npm package

**Comment by Ines-K** [comment]
Hi,

I just got Kadira and wanted to deploy my meteor app and here's what I got:

✘ Invoking deployment process: FAILED
	
	-----------------------------------STDERR-----------------------------------
	yp info spawn args   '-Dmodule_root_dir=/opt/cuttocontenttemp/tmp/bundle/programs/server/npm/meteorhacks:kadira-binary-deps/node_modules/usage',
	gyp info spawn args   '--depth=.',
	gyp info spawn args   '--no-parallel',
	gyp info spawn args   '--generator-output',
	gyp info spawn args   'build',
	gyp info spawn args   '-Goutput_dir=.' ]
	gyp ERR! build error 
	gyp ERR! stack Error: not found: make
	gyp ERR! stack     at F (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:38:28)
	gyp ERR! stack     at E (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:41:29)
	gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/which/which.js:52:16
	gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
	gyp ERR! System Linux 3.16.0-28-generic
	gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
	gyp ERR! cwd /opt/cuttocontenttemp/tmp/bundle/programs/server/npm/meteorhacks:kadira-binary-deps/node_modules/usage
	gyp ERR! node -v v0.10.33
	gyp ERR! node-gyp -v v1.0.2
	gyp ERR! not ok 
	-----------------------------------STDOUT-----------------------------------
	=> re-installing binary npm module 'usage' of package 'meteorhacks:kadira-binary-deps'
	----------------------------------------------------------------------------
Completed TaskList: Deploy app 'cuttocontenttemp' (linux)

**Comment by arunoda** [comment]
Okay.
You need to install devtools.
If you are ubuntu install via: *sudo apt-get install build-essential*

If you are not in ubuntu, let me know the OS.

**Comment by imran-aspire** [comment]
cool it's works , Thanks
